pipeline {

  agent any

  environment {
    AWS_REGION = "us-east-1"
    ECR_REPO = "<ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/expense-backend"
  }

  stages {

    stage('Checkout') {
      steps {
        git 'https://github.com/YOUR_REPO_URL.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t expense-app ./app'
      }
    }

    stage('Login to ECR') {
      steps {
        sh '''
        aws ecr get-login-password --region $AWS_REGION \
        | docker login \
        --username AWS \
        --password-stdin $ECR_REPO
        '''
      }
    }

    stage('Tag Image') {
      steps {
        sh 'docker tag expense-app:latest $ECR_REPO:latest'
      }
    }

    stage('Push Image') {
      steps {
        sh 'docker push $ECR_REPO:latest'
      }
    }

    stage('Deploy to EKS') {
      steps {
        sh 'kubectl apply -f k8s/'
      }
    }

  }

}